# Site settings
title: Ben Mathews
email: ben@mathews2000.com
description: > # this means to ignore newlines until "baseurl:"
  My musings on family, politics, religion, software engineering,
  and anything else I want.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mathews2000.com" 
twitter_username: benmathews
github_username:  benmathews

# Build settings
markdown: kramdown
